version: '3.1'

services:
  mongodb:
    image: mongo:8.0.3
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: mtcdb           # Nome do banco de dados padrão
    volumes:
      - mtcdb:/data/db                  # Volume para persistência de dados

volumes:
  mtcdb: # Declaração do volume nomeado
